// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: session/aes.proto

package session

import (
	common "github.com/enproto/go-enproto/pb/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AES-GCM based message communication packet
type AESGCMPacket struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version    *common.Version          `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`                         // Protocol version
	Timestamp  *common.Timestamp        `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                     // Epoch milliseconds
	Nonce      *common.Nonce            `protobuf:"bytes,3,opt,name=nonce,proto3" json:"nonce,omitempty"`                             // 12-byte IV used for AES-GCM
	CipherText *common.EncryptedMessage `protobuf:"bytes,4,opt,name=cipher_text,json=cipherText,proto3" json:"cipher_text,omitempty"` // AES-GCM encrypted data
	AuthTag    *common.AuthTag          `protobuf:"bytes,5,opt,name=auth_tag,json=authTag,proto3" json:"auth_tag,omitempty"`          // 16-byte GCM authentication tag
}

func (x *AESGCMPacket) Reset() {
	*x = AESGCMPacket{}
	if protoimpl.UnsafeEnabled {
		mi := &file_session_aes_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AESGCMPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AESGCMPacket) ProtoMessage() {}

func (x *AESGCMPacket) ProtoReflect() protoreflect.Message {
	mi := &file_session_aes_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AESGCMPacket.ProtoReflect.Descriptor instead.
func (*AESGCMPacket) Descriptor() ([]byte, []int) {
	return file_session_aes_proto_rawDescGZIP(), []int{0}
}

func (x *AESGCMPacket) GetVersion() *common.Version {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *AESGCMPacket) GetTimestamp() *common.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *AESGCMPacket) GetNonce() *common.Nonce {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *AESGCMPacket) GetCipherText() *common.EncryptedMessage {
	if x != nil {
		return x.CipherText
	}
	return nil
}

func (x *AESGCMPacket) GetAuthTag() *common.AuthTag {
	if x != nil {
		return x.AuthTag
	}
	return nil
}

var File_session_aes_proto protoreflect.FileDescriptor

var file_session_aes_proto_rawDesc = []byte{
	0x0a, 0x11, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x2f, 0x61, 0x65, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x73, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x1a, 0x12, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x74, 0x79, 0x70,
	0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x9e, 0x02, 0x0a, 0x0c, 0x41, 0x45, 0x53,
	0x47, 0x43, 0x4d, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x31, 0x0a, 0x07, 0x76, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x65, 0x6e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x56, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x37, 0x0a, 0x09,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x19, 0x2e, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x2b, 0x0a, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x4e, 0x6f, 0x6e, 0x63, 0x65, 0x52, 0x05, 0x6e, 0x6f, 0x6e,
	0x63, 0x65, 0x12, 0x41, 0x0a, 0x0b, 0x63, 0x69, 0x70, 0x68, 0x65, 0x72, 0x5f, 0x74, 0x65, 0x78,
	0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74,
	0x65, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x0a, 0x63, 0x69, 0x70, 0x68, 0x65,
	0x72, 0x54, 0x65, 0x78, 0x74, 0x12, 0x32, 0x0a, 0x08, 0x61, 0x75, 0x74, 0x68, 0x5f, 0x74, 0x61,
	0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x54, 0x61, 0x67,
	0x52, 0x07, 0x61, 0x75, 0x74, 0x68, 0x54, 0x61, 0x67, 0x42, 0x32, 0x5a, 0x30, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x67, 0x6f, 0x2d, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x62, 0x2f, 0x73, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x3b, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_session_aes_proto_rawDescOnce sync.Once
	file_session_aes_proto_rawDescData = file_session_aes_proto_rawDesc
)

func file_session_aes_proto_rawDescGZIP() []byte {
	file_session_aes_proto_rawDescOnce.Do(func() {
		file_session_aes_proto_rawDescData = protoimpl.X.CompressGZIP(file_session_aes_proto_rawDescData)
	})
	return file_session_aes_proto_rawDescData
}

var file_session_aes_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_session_aes_proto_goTypes = []interface{}{
	(*AESGCMPacket)(nil),            // 0: enproto.session.AESGCMPacket
	(*common.Version)(nil),          // 1: enproto.common.Version
	(*common.Timestamp)(nil),        // 2: enproto.common.Timestamp
	(*common.Nonce)(nil),            // 3: enproto.common.Nonce
	(*common.EncryptedMessage)(nil), // 4: enproto.common.EncryptedMessage
	(*common.AuthTag)(nil),          // 5: enproto.common.AuthTag
}
var file_session_aes_proto_depIdxs = []int32{
	1, // 0: enproto.session.AESGCMPacket.version:type_name -> enproto.common.Version
	2, // 1: enproto.session.AESGCMPacket.timestamp:type_name -> enproto.common.Timestamp
	3, // 2: enproto.session.AESGCMPacket.nonce:type_name -> enproto.common.Nonce
	4, // 3: enproto.session.AESGCMPacket.cipher_text:type_name -> enproto.common.EncryptedMessage
	5, // 4: enproto.session.AESGCMPacket.auth_tag:type_name -> enproto.common.AuthTag
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_session_aes_proto_init() }
func file_session_aes_proto_init() {
	if File_session_aes_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_session_aes_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AESGCMPacket); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_session_aes_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_session_aes_proto_goTypes,
		DependencyIndexes: file_session_aes_proto_depIdxs,
		MessageInfos:      file_session_aes_proto_msgTypes,
	}.Build()
	File_session_aes_proto = out.File
	file_session_aes_proto_rawDesc = nil
	file_session_aes_proto_goTypes = nil
	file_session_aes_proto_depIdxs = nil
}
