// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: session/rsa.proto

package session

import (
	common "github.com/enproto/go-enproto/pb/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Metadata for initiating an RSA-based session
type RSAClientPacket struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Version             *common.Version        `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`                                                      // Protocol version
	Timestamp           *common.Timestamp      `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                                  // Epoch milliseconds
	Nonce               *common.Nonce          `protobuf:"bytes,3,opt,name=nonce,proto3" json:"nonce,omitempty"`                                                          // Unique nonce
	ClientId            *common.ClientID       `protobuf:"bytes,4,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`                                    // Optional client identifier
	ClientSessionPubkey []byte                 `protobuf:"bytes,5,opt,name=client_session_pubkey,json=clientSessionPubkey,proto3" json:"client_session_pubkey,omitempty"` // Ephemeral public key (e.g., x25519 or RSA)
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RSAClientPacket) Reset() {
	*x = RSAClientPacket{}
	mi := &file_session_rsa_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RSAClientPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RSAClientPacket) ProtoMessage() {}

func (x *RSAClientPacket) ProtoReflect() protoreflect.Message {
	mi := &file_session_rsa_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RSAClientPacket.ProtoReflect.Descriptor instead.
func (*RSAClientPacket) Descriptor() ([]byte, []int) {
	return file_session_rsa_proto_rawDescGZIP(), []int{0}
}

func (x *RSAClientPacket) GetVersion() *common.Version {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *RSAClientPacket) GetTimestamp() *common.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *RSAClientPacket) GetNonce() *common.Nonce {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *RSAClientPacket) GetClientId() *common.ClientID {
	if x != nil {
		return x.ClientId
	}
	return nil
}

func (x *RSAClientPacket) GetClientSessionPubkey() []byte {
	if x != nil {
		return x.ClientSessionPubkey
	}
	return nil
}

// RSA-encrypted RSAClientPacket
type RSAClientEncryptedPacket struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	EncryptedPayload []byte                 `protobuf:"bytes,1,opt,name=encrypted_payload,json=encryptedPayload,proto3" json:"encrypted_payload,omitempty"` // Encrypted with server's RSA public key
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RSAClientEncryptedPacket) Reset() {
	*x = RSAClientEncryptedPacket{}
	mi := &file_session_rsa_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RSAClientEncryptedPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RSAClientEncryptedPacket) ProtoMessage() {}

func (x *RSAClientEncryptedPacket) ProtoReflect() protoreflect.Message {
	mi := &file_session_rsa_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RSAClientEncryptedPacket.ProtoReflect.Descriptor instead.
func (*RSAClientEncryptedPacket) Descriptor() ([]byte, []int) {
	return file_session_rsa_proto_rawDescGZIP(), []int{1}
}

func (x *RSAClientEncryptedPacket) GetEncryptedPayload() []byte {
	if x != nil {
		return x.EncryptedPayload
	}
	return nil
}

// Server handshake response (can be signed or encrypted)
type RSAServerPacket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *common.Timestamp      `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                  // Epoch milliseconds
	Nonce         *common.Nonce          `protobuf:"bytes,2,opt,name=nonce,proto3" json:"nonce,omitempty"`                          // Echo of client nonce or newly generated
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // Unique session identifier
	Signature     []byte                 `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`                  // Server signature (optional)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RSAServerPacket) Reset() {
	*x = RSAServerPacket{}
	mi := &file_session_rsa_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RSAServerPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RSAServerPacket) ProtoMessage() {}

func (x *RSAServerPacket) ProtoReflect() protoreflect.Message {
	mi := &file_session_rsa_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RSAServerPacket.ProtoReflect.Descriptor instead.
func (*RSAServerPacket) Descriptor() ([]byte, []int) {
	return file_session_rsa_proto_rawDescGZIP(), []int{2}
}

func (x *RSAServerPacket) GetTimestamp() *common.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *RSAServerPacket) GetNonce() *common.Nonce {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *RSAServerPacket) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RSAServerPacket) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// RSA-encrypted RSAServerPacket (optional, for confidentiality)
type RSAServerEncryptedPacket struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	EncryptedPayload []byte                 `protobuf:"bytes,1,opt,name=encrypted_payload,json=encryptedPayload,proto3" json:"encrypted_payload,omitempty"` // Encrypted with client's ephemeral public key
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RSAServerEncryptedPacket) Reset() {
	*x = RSAServerEncryptedPacket{}
	mi := &file_session_rsa_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RSAServerEncryptedPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RSAServerEncryptedPacket) ProtoMessage() {}

func (x *RSAServerEncryptedPacket) ProtoReflect() protoreflect.Message {
	mi := &file_session_rsa_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RSAServerEncryptedPacket.ProtoReflect.Descriptor instead.
func (*RSAServerEncryptedPacket) Descriptor() ([]byte, []int) {
	return file_session_rsa_proto_rawDescGZIP(), []int{3}
}

func (x *RSAServerEncryptedPacket) GetEncryptedPayload() []byte {
	if x != nil {
		return x.EncryptedPayload
	}
	return nil
}

var File_session_rsa_proto protoreflect.FileDescriptor

const file_session_rsa_proto_rawDesc = "" +
	"\n" +
	"\x11session/rsa.proto\x12\x0fenproto.session\x1a\x12common/types.proto\"\x95\x02\n" +
	"\x0fRSAClientPacket\x121\n" +
	"\aversion\x18\x01 \x01(\v2\x17.enproto.common.VersionR\aversion\x127\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x19.enproto.common.TimestampR\ttimestamp\x12+\n" +
	"\x05nonce\x18\x03 \x01(\v2\x15.enproto.common.NonceR\x05nonce\x125\n" +
	"\tclient_id\x18\x04 \x01(\v2\x18.enproto.common.ClientIDR\bclientId\x122\n" +
	"\x15client_session_pubkey\x18\x05 \x01(\fR\x13clientSessionPubkey\"G\n" +
	"\x18RSAClientEncryptedPacket\x12+\n" +
	"\x11encrypted_payload\x18\x01 \x01(\fR\x10encryptedPayload\"\xb4\x01\n" +
	"\x0fRSAServerPacket\x127\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x19.enproto.common.TimestampR\ttimestamp\x12+\n" +
	"\x05nonce\x18\x02 \x01(\v2\x15.enproto.common.NonceR\x05nonce\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12\x1c\n" +
	"\tsignature\x18\x04 \x01(\fR\tsignature\"G\n" +
	"\x18RSAServerEncryptedPacket\x12+\n" +
	"\x11encrypted_payload\x18\x01 \x01(\fR\x10encryptedPayloadB2Z0github.com/enproto/go-enproto/pb/session;sessionb\x06proto3"

var (
	file_session_rsa_proto_rawDescOnce sync.Once
	file_session_rsa_proto_rawDescData []byte
)

func file_session_rsa_proto_rawDescGZIP() []byte {
	file_session_rsa_proto_rawDescOnce.Do(func() {
		file_session_rsa_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_session_rsa_proto_rawDesc), len(file_session_rsa_proto_rawDesc)))
	})
	return file_session_rsa_proto_rawDescData
}

var file_session_rsa_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_session_rsa_proto_goTypes = []any{
	(*RSAClientPacket)(nil),          // 0: enproto.session.RSAClientPacket
	(*RSAClientEncryptedPacket)(nil), // 1: enproto.session.RSAClientEncryptedPacket
	(*RSAServerPacket)(nil),          // 2: enproto.session.RSAServerPacket
	(*RSAServerEncryptedPacket)(nil), // 3: enproto.session.RSAServerEncryptedPacket
	(*common.Version)(nil),           // 4: enproto.common.Version
	(*common.Timestamp)(nil),         // 5: enproto.common.Timestamp
	(*common.Nonce)(nil),             // 6: enproto.common.Nonce
	(*common.ClientID)(nil),          // 7: enproto.common.ClientID
}
var file_session_rsa_proto_depIdxs = []int32{
	4, // 0: enproto.session.RSAClientPacket.version:type_name -> enproto.common.Version
	5, // 1: enproto.session.RSAClientPacket.timestamp:type_name -> enproto.common.Timestamp
	6, // 2: enproto.session.RSAClientPacket.nonce:type_name -> enproto.common.Nonce
	7, // 3: enproto.session.RSAClientPacket.client_id:type_name -> enproto.common.ClientID
	5, // 4: enproto.session.RSAServerPacket.timestamp:type_name -> enproto.common.Timestamp
	6, // 5: enproto.session.RSAServerPacket.nonce:type_name -> enproto.common.Nonce
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_session_rsa_proto_init() }
func file_session_rsa_proto_init() {
	if File_session_rsa_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_session_rsa_proto_rawDesc), len(file_session_rsa_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_session_rsa_proto_goTypes,
		DependencyIndexes: file_session_rsa_proto_depIdxs,
		MessageInfos:      file_session_rsa_proto_msgTypes,
	}.Build()
	File_session_rsa_proto = out.File
	file_session_rsa_proto_goTypes = nil
	file_session_rsa_proto_depIdxs = nil
}
