// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: session/rsa.proto

package session

import (
	common "github.com/enproto/go-enproto/pb/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Metadata for initiating an RSA-based session
type RSAClientPacket struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version             *common.Version   `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`                                                      // Protocol version
	Timestamp           *common.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                                  // Epoch milliseconds
	Nonce               *common.Nonce     `protobuf:"bytes,3,opt,name=nonce,proto3" json:"nonce,omitempty"`                                                          // Unique nonce
	ClientId            *common.ClientID  `protobuf:"bytes,4,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`                                    // Optional client identifier
	ClientSessionPubkey *common.Key       `protobuf:"bytes,5,opt,name=client_session_pubkey,json=clientSessionPubkey,proto3" json:"client_session_pubkey,omitempty"` // Ephemeral public key (e.g., x25519 or RSA)
}

func (x *RSAClientPacket) Reset() {
	*x = RSAClientPacket{}
	if protoimpl.UnsafeEnabled {
		mi := &file_session_rsa_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RSAClientPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RSAClientPacket) ProtoMessage() {}

func (x *RSAClientPacket) ProtoReflect() protoreflect.Message {
	mi := &file_session_rsa_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RSAClientPacket.ProtoReflect.Descriptor instead.
func (*RSAClientPacket) Descriptor() ([]byte, []int) {
	return file_session_rsa_proto_rawDescGZIP(), []int{0}
}

func (x *RSAClientPacket) GetVersion() *common.Version {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *RSAClientPacket) GetTimestamp() *common.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *RSAClientPacket) GetNonce() *common.Nonce {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *RSAClientPacket) GetClientId() *common.ClientID {
	if x != nil {
		return x.ClientId
	}
	return nil
}

func (x *RSAClientPacket) GetClientSessionPubkey() *common.Key {
	if x != nil {
		return x.ClientSessionPubkey
	}
	return nil
}

// RSA-encrypted RSAClientPacket
type RSAClientEncryptedPacket struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EncryptedPayload *common.EncryptedMessage `protobuf:"bytes,1,opt,name=encrypted_payload,json=encryptedPayload,proto3" json:"encrypted_payload,omitempty"` // Encrypted with server's RSA public key
}

func (x *RSAClientEncryptedPacket) Reset() {
	*x = RSAClientEncryptedPacket{}
	if protoimpl.UnsafeEnabled {
		mi := &file_session_rsa_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RSAClientEncryptedPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RSAClientEncryptedPacket) ProtoMessage() {}

func (x *RSAClientEncryptedPacket) ProtoReflect() protoreflect.Message {
	mi := &file_session_rsa_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RSAClientEncryptedPacket.ProtoReflect.Descriptor instead.
func (*RSAClientEncryptedPacket) Descriptor() ([]byte, []int) {
	return file_session_rsa_proto_rawDescGZIP(), []int{1}
}

func (x *RSAClientEncryptedPacket) GetEncryptedPayload() *common.EncryptedMessage {
	if x != nil {
		return x.EncryptedPayload
	}
	return nil
}

// Server handshake response (can be signed or encrypted)
type RSAServerPacket struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp *common.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                  // Epoch milliseconds
	Nonce     *common.Nonce     `protobuf:"bytes,2,opt,name=nonce,proto3" json:"nonce,omitempty"`                          // Echo of client nonce or newly generated
	SessionId *common.SessionID `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // Unique session identifier
	Signature *common.Signature `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`                  // Server signature (optional)
}

func (x *RSAServerPacket) Reset() {
	*x = RSAServerPacket{}
	if protoimpl.UnsafeEnabled {
		mi := &file_session_rsa_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RSAServerPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RSAServerPacket) ProtoMessage() {}

func (x *RSAServerPacket) ProtoReflect() protoreflect.Message {
	mi := &file_session_rsa_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RSAServerPacket.ProtoReflect.Descriptor instead.
func (*RSAServerPacket) Descriptor() ([]byte, []int) {
	return file_session_rsa_proto_rawDescGZIP(), []int{2}
}

func (x *RSAServerPacket) GetTimestamp() *common.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *RSAServerPacket) GetNonce() *common.Nonce {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *RSAServerPacket) GetSessionId() *common.SessionID {
	if x != nil {
		return x.SessionId
	}
	return nil
}

func (x *RSAServerPacket) GetSignature() *common.Signature {
	if x != nil {
		return x.Signature
	}
	return nil
}

// RSA-encrypted RSAServerPacket (optional, for confidentiality)
type RSAServerEncryptedPacket struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EncryptedPayload *common.EncryptedMessage `protobuf:"bytes,1,opt,name=encrypted_payload,json=encryptedPayload,proto3" json:"encrypted_payload,omitempty"` // Encrypted with client's ephemeral public key
}

func (x *RSAServerEncryptedPacket) Reset() {
	*x = RSAServerEncryptedPacket{}
	if protoimpl.UnsafeEnabled {
		mi := &file_session_rsa_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RSAServerEncryptedPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RSAServerEncryptedPacket) ProtoMessage() {}

func (x *RSAServerEncryptedPacket) ProtoReflect() protoreflect.Message {
	mi := &file_session_rsa_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RSAServerEncryptedPacket.ProtoReflect.Descriptor instead.
func (*RSAServerEncryptedPacket) Descriptor() ([]byte, []int) {
	return file_session_rsa_proto_rawDescGZIP(), []int{3}
}

func (x *RSAServerEncryptedPacket) GetEncryptedPayload() *common.EncryptedMessage {
	if x != nil {
		return x.EncryptedPayload
	}
	return nil
}

var File_session_rsa_proto protoreflect.FileDescriptor

var file_session_rsa_proto_rawDesc = []byte{
	0x0a, 0x11, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x2f, 0x72, 0x73, 0x61, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x73, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x1a, 0x12, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x74, 0x79, 0x70,
	0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xaa, 0x02, 0x0a, 0x0f, 0x52, 0x53, 0x41,
	0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x31, 0x0a, 0x07,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e,
	0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x56,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12,
	0x37, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x19, 0x2e, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x2b, 0x0a, 0x05, 0x6e, 0x6f, 0x6e, 0x63,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x4e, 0x6f, 0x6e, 0x63, 0x65, 0x52, 0x05,
	0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x12, 0x35, 0x0a, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f,
	0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x65, 0x6e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x49, 0x44, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x47, 0x0a, 0x15,
	0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x70,
	0x75, 0x62, 0x6b, 0x65, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x65, 0x6e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x4b, 0x65, 0x79,
	0x52, 0x13, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x50,
	0x75, 0x62, 0x6b, 0x65, 0x79, 0x22, 0x69, 0x0a, 0x18, 0x52, 0x53, 0x41, 0x43, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x65, 0x64, 0x50, 0x61, 0x63, 0x6b, 0x65,
	0x74, 0x12, 0x4d, 0x0a, 0x11, 0x65, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x65, 0x64, 0x5f, 0x70,
	0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x65,
	0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x45, 0x6e,
	0x63, 0x72, 0x79, 0x70, 0x74, 0x65, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x10,
	0x65, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x65, 0x64, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64,
	0x22, 0xea, 0x01, 0x0a, 0x0f, 0x52, 0x53, 0x41, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x50, 0x61,
	0x63, 0x6b, 0x65, 0x74, 0x12, 0x37, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x2b, 0x0a,
	0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x65,
	0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x4e, 0x6f,
	0x6e, 0x63, 0x65, 0x52, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x12, 0x38, 0x0a, 0x0a, 0x73, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19,
	0x2e, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e,
	0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x49, 0x64, 0x12, 0x37, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75,
	0x72, 0x65, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x22, 0x69, 0x0a,
	0x18, 0x52, 0x53, 0x41, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70,
	0x74, 0x65, 0x64, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x4d, 0x0a, 0x11, 0x65, 0x6e, 0x63,
	0x72, 0x79, 0x70, 0x74, 0x65, 0x64, 0x5f, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x65, 0x64, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x10, 0x65, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x65,
	0x64, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x42, 0x32, 0x5a, 0x30, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67,
	0x6f, 0x2d, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x62, 0x2f, 0x73, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x3b, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_session_rsa_proto_rawDescOnce sync.Once
	file_session_rsa_proto_rawDescData = file_session_rsa_proto_rawDesc
)

func file_session_rsa_proto_rawDescGZIP() []byte {
	file_session_rsa_proto_rawDescOnce.Do(func() {
		file_session_rsa_proto_rawDescData = protoimpl.X.CompressGZIP(file_session_rsa_proto_rawDescData)
	})
	return file_session_rsa_proto_rawDescData
}

var file_session_rsa_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_session_rsa_proto_goTypes = []interface{}{
	(*RSAClientPacket)(nil),          // 0: enproto.session.RSAClientPacket
	(*RSAClientEncryptedPacket)(nil), // 1: enproto.session.RSAClientEncryptedPacket
	(*RSAServerPacket)(nil),          // 2: enproto.session.RSAServerPacket
	(*RSAServerEncryptedPacket)(nil), // 3: enproto.session.RSAServerEncryptedPacket
	(*common.Version)(nil),           // 4: enproto.common.Version
	(*common.Timestamp)(nil),         // 5: enproto.common.Timestamp
	(*common.Nonce)(nil),             // 6: enproto.common.Nonce
	(*common.ClientID)(nil),          // 7: enproto.common.ClientID
	(*common.Key)(nil),               // 8: enproto.common.Key
	(*common.EncryptedMessage)(nil),  // 9: enproto.common.EncryptedMessage
	(*common.SessionID)(nil),         // 10: enproto.common.SessionID
	(*common.Signature)(nil),         // 11: enproto.common.Signature
}
var file_session_rsa_proto_depIdxs = []int32{
	4,  // 0: enproto.session.RSAClientPacket.version:type_name -> enproto.common.Version
	5,  // 1: enproto.session.RSAClientPacket.timestamp:type_name -> enproto.common.Timestamp
	6,  // 2: enproto.session.RSAClientPacket.nonce:type_name -> enproto.common.Nonce
	7,  // 3: enproto.session.RSAClientPacket.client_id:type_name -> enproto.common.ClientID
	8,  // 4: enproto.session.RSAClientPacket.client_session_pubkey:type_name -> enproto.common.Key
	9,  // 5: enproto.session.RSAClientEncryptedPacket.encrypted_payload:type_name -> enproto.common.EncryptedMessage
	5,  // 6: enproto.session.RSAServerPacket.timestamp:type_name -> enproto.common.Timestamp
	6,  // 7: enproto.session.RSAServerPacket.nonce:type_name -> enproto.common.Nonce
	10, // 8: enproto.session.RSAServerPacket.session_id:type_name -> enproto.common.SessionID
	11, // 9: enproto.session.RSAServerPacket.signature:type_name -> enproto.common.Signature
	9,  // 10: enproto.session.RSAServerEncryptedPacket.encrypted_payload:type_name -> enproto.common.EncryptedMessage
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_session_rsa_proto_init() }
func file_session_rsa_proto_init() {
	if File_session_rsa_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_session_rsa_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RSAClientPacket); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_session_rsa_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RSAClientEncryptedPacket); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_session_rsa_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RSAServerPacket); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_session_rsa_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RSAServerEncryptedPacket); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_session_rsa_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_session_rsa_proto_goTypes,
		DependencyIndexes: file_session_rsa_proto_depIdxs,
		MessageInfos:      file_session_rsa_proto_msgTypes,
	}.Build()
	File_session_rsa_proto = out.File
	file_session_rsa_proto_rawDesc = nil
	file_session_rsa_proto_goTypes = nil
	file_session_rsa_proto_depIdxs = nil
}
